remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: One-viz
description: AI-Powered Interactive Data Visualization for Everyone
long_description: "One-viz is an open-source library of framework-agnostic web components for building interactive data visualizations, powered by a GenAI conversational engine."

markdown: kramdown
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

# Exclude files from the build
exclude:
  - package.json
  - package-lock.json
  - tsconfig.json
  - .gitignore
  - src/
  - node_modules/
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE

url: "https://josephaxisa.github.io" 
baseurl: "/one-viz"

permalink: pretty
